issueTrackerURL = "https://github.com/nexusnode/crafting-dead/issues"
license = "GPL v3.0"
loaderVersion = "[27,)"
modLoader = "javafml"

[[mods]]
authors = "Hallzmine"
credits = "Hallzmine, hallmine"
description = '''
    A mod created to add loot piles to Crafting Dead 1.16+.
'''
displayName = "Crafting Dead Loot"
displayURL = "www.craftingdead.com"
modId = "hcdservercore"
version = "${file.jarVersion}"

[[dependencies.hcdservercore]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hcdservercore]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
